### PR TITLE
Commit assignment-2

### PR DESCRIPTION
**Pull request by sbl-management**
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by anjali-deshpande-hub — CHANGES_REQUESTED** [review]
Well done.

Just a few minor changes:
Question 1: Correct the indentation of this code:
```
with open(all_paths[0], 'r') as f:
    # YOUR CODE HERE: Use the readline() or readlines() method to read the .csv file into 'contents'
    print(f.readlines())
    # YOUR CODE HERE: Iterate through 'contents' using a for loop and print each row for inspection
    for file_path in all_paths:
       with open(file_path, 'r') as f:
          print(f.readline())
```
Making it indented inside 'with' implies that you are using the for loop for that file handle. But its independent of that. This is for better readability and maintainability of code.

Question 3: There is duplication of code here under the testing section. We don't need to redefine check_zeros and patient_summary functions.

Please correct the above mentioned items and resubmit. Everything else looks good

**Comment by sbl-management** [comment]
> Well done.
> 
> Just a few minor changes: Question 1: Correct the indentation of this code:
> 
> ```
> with open(all_paths[0], 'r') as f:
>     # YOUR CODE HERE: Use the readline() or readlines() method to read the .csv file into 'contents'
>     print(f.readlines())
>     # YOUR CODE HERE: Iterate through 'contents' using a for loop and print each row for inspection
>     for file_path in all_paths:
>        with open(file_path, 'r') as f:
>           print(f.readline())
> ```
> 
> Making it indented inside 'with' implies that you are using the for loop for that file handle. But its independent of that. This is for better readability and maintainability of code.
> 
> Question 3: There is duplication of code here under the testing section. We don't need to redefine check_zeros and patient_summary functions.
> 
> Please correct the above mentioned items and resubmit. Everything else looks good

Hi, I have updated my code. Please review.

**Review by anjali-deshpande-hub — COMMENTED** [review]
For future, please don't merge the code or close the PR until the PR is re-reviewed and marked approved. Thank you!.

**Comment by anjali-deshpande-hub** [comment]
The review changes were successfully completed. (Note The PR could not be marked 'Approved' because the PR was closed.)

**Pull request merged**
